modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="ars_meko"
version="1.0"
displayName="Mekanism Ars Nouveau Integration"
authors="msdoggirl"
[[dependencies.mekvamp]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekvamp]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekvamp]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[1.10,)"
    ordering="AFTER"
    side="BOTH"
